### PR TITLE
Fix index parsing bug

### LINKED ISSUE #199: Edit c and Edit p command only support one-digit index
Screenshot 2023-11-08 at 12 23 22 AM
The substring truncated has only one character, which means that the index can only be one-digit.

### PR DESCRIPTION
**Pull request by lunaroddity**
Edit the preamble check to check for non-integer values

Closes #199

### CODE REVIEW

**Review by Tim-Siu — APPROVED** [review]
This looks good to me. Let's see what @li-rongzhi thinks.

File: src/main/java/seedu/address/logic/parser/EditCommandParser.java [hunk 1]
```diff
@@ -140,8 +140,8 @@ public Index parseIndexToEdit(String args) throws ParseException {
         Index index = null;
 
         try {
-            String indexStr = args.substring(2, 3);
-            index = ParserUtil.parseIndex(indexStr);
+            String[] splitArgs = args.split(" ", 3);
+            index = ParserUtil.parseIndex(splitArgs[1]);
         } catch (ParseException pe) {
             throw new ParseException(
                     String.format(MESSAGE_INVALID_COMMAND_FORMAT, EditPersonCommand.MESSAGE_USAGE), pe);
```
Comment (rngzhi) [inline src/main/java/seedu/address/logic/parser/EditCommandParser.java:147]: Maybe we can replace the exception message with the one for invalid index?

Comment (Tim-Siu) [reply src/main/java/seedu/address/logic/parser/EditCommandParser.java:147]: Unfortunately, we have to keep it as it was in v1.3 due to feature freeze issue.
