### PR TITLE
Fix issues related to sort and find

### LINKED ISSUE #152: [PE-D][Tester E] Input validation for Name field is not sufficient
Contacts with `name` field can be added even if it is purely numeric. 

The command used: `add p n/1 p/98765432 e/johnd@example.com a/311, Clementi Ave 2, #02-25`

-------------
Labels: `type.FeatureFlaw` `severity.Medium`
original: nreHieW/ped#5

### LINKED ISSUE #165: [PE-D][Tester E] Multiple start fields can be provided in the sort and filter command
Multiple start fields can be provided and it appears that the program will simply use the latter one. 

Screenshot:

Command used: `sort c start/01-02-2024 00:01 start/01-02-2023 00:00 end/01-02-2024 00:00`

-------------
Labels: `severity.High` `type.FunctionalityBug`
original: nreHieW/ped#10

### LINKED ISSUE #170: [PE-D][Tester D] "sort" feature doesn't seem to work as advertised
This seems to be the result I get when I enter this command (note that the screenshot below is after I clicked enter, but there was no acknowledgment or error message provided, only slight GUI changes in the "Companies" tab). 

According to the UG, this command seems like it is supposed to filter out other companies that do not meet the input specification.

However, currently all the companies are listed alongside the actual companies that I want to filter.

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: limzhenwy/ped#8

### LINKED ISSUE #187: [PE-D][Tester C] No feedback from UI for invalid input for find command
### No feedback from UI for invalid input for find command

I entered the invalid command `find c google llc` which is invalid as it contains spaces. However, I did not get any error messages despite pressing "enter" on my keyboard multiple times, and the command finally worked after removing the space in the company name. I suggest to check for a bug caused while parsing the input, and if no bugs are present, an appropriate error message to remind the user should be returned.

<i><video controls><source src="https://raw.githubusercontent.com/kohkaijie/ped/main/files/e8849cda-f0a0-4aab-aa05-6fa3979b6055.mp4" type="video/mp4">Your browser does not support the video tag.</video><br>video:https://raw.githubusercontent.com/kohkaijie/ped/main/files/e8849cda-f0a0-4aab-aa05-6fa3979b6055.mp4</i>

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: kohkaijie/ped#8

### LINKED ISSUE #188: [PE-D][Tester C] Invalid input for start and end time allowed for sort companies command
### Invalid input for start and end time allowed for sort companies command

I entered the following command `sort c start/01-05-2024 00:01 end/01-04-2024 00:01`. This should be an invalid input as specified by the UG, since the start date is later than the end date, and thus return no companies. However, the command was succesful and a company was returned by the command.

<i><video controls><source src="https://raw.githubusercontent.com/kohkaijie/ped/main/files/7716876d-9e25-4ffd-affd-7c55c5442f15.mp4" type="video/mp4">Your browser does not support the video tag.</video><br>video:https://raw.githubusercontent.com/kohkaijie/ped/main/files/7716876d-9e25-4ffd-affd-7c55c5442f15.mp4</i>

-------------
Labels: `severity.High` `type.FunctionalityBug`
original: kohkaijie/ped#9

### LINKED ISSUE #192: [PE-D][Tester A] Can add warnings for handling potentially invalid date time
As mentioned in the UG, there is no error handling for potentially invalid date time inputs, such as being to input an end date that is earlier than the start date for `sort c`, however, might be nice to have a warning or note instead.

-------------
Labels: `severity.VeryLow` `type.FeatureFlaw`
original: J-hta-n/ped#7

### LINKED ISSUE #198: Integer.MAX_VALUE limitation
Maybe we can mention in UG/DG that the app can work with at most 2147483647 people/persons. Also, the error messages are affected.

### PR DESCRIPTION
**Pull request by Tim-Siu**
Fix issues related to sort and find

- Resolved #192
- Resolved #188
- Resolved #170
- Resolved #152
- Resolved #165
- Resolved #187 

#170 was likely caused by problems with two consecutive sort commands

### CODE REVIEW

File: src/main/java/seedu/address/logic/Messages.java [hunk 1]
```diff
@@ -23,6 +23,17 @@ public class Messages {
...
+    public static final String MESSAGE_INVALID_END_TIME = "The end time is before the start time!";
+    // Message that the DataTime is not in the correct format
+    public static final String MESSAGE_INVALID_DATETIME_FORMAT = "The date time is not in the correct format! We expect"
+            + " the format to be  dd-MM-yyyy HH:mm.";
+    // Message for find command that the name keyword is illegal
+    public static final String MESSAGE_INVALID_NAME_KEYWORD = "The name keyword is illegal! We expect the name keyword"
+            + " to be a single word (alphabetical characters only).";
+    // Message for find command that the tag keyword is illegal
+    public static final String MESSAGE_INVALID_TAG_KEYWORD = "The tag keyword is illegal! We expect the tag keyword"
+            + " to be a single word (alphanumeric characters only).";
```
Comment (lunaroddity) [inline src/main/java/seedu/address/logic/Messages.java]: I think we need to ask James about this because they mentioned that changing the output of the UI is changing the feature

File: src/main/java/seedu/address/logic/parser/FindCommandParser.java [hunk 2]
```diff
@@ -65,6 +67,21 @@ public FindCommand parse(String args) throws ParseException {
             List<String> nameKeywordsList = new ArrayList<>(nameKeywords);
             List<String> tagKeywordsList = new ArrayList<>(tagKeywords);
 
+            // Go through the list to find if nameKeyword is pure
+            // alphabets and tagKeywords are pure alphanumeric without any spaces
+            for (String nameKeyword : nameKeywordsList) {
+                if (!nameKeyword.matches("^[a-zA-Z]*$") || nameKeyword.isBlank()) {
+                    throw new ParseException(
+                        MESSAGE_INVALID_NAME_KEYWORD);
```
Comment (lunaroddity) [inline src/main/java/seedu/address/logic/parser/FindCommandParser.java]: I feel like this line break is unnecessary since it fits within 120 characters

File: src/main/java/seedu/address/logic/parser/FindCommandParser.java [hunk 3]
```diff
@@ -65,6 +67,21 @@ public FindCommand parse(String args) throws ParseException {
...
+                }
+            }
+            for (String tagKeyword : tagKeywordsList) {
+                if (!tagKeyword.matches("^[a-zA-Z0-9]*$") || tagKeyword.isBlank()) {
+                    throw new ParseException(
+                        MESSAGE_INVALID_TAG_KEYWORD);
```
Comment (lunaroddity) [inline src/main/java/seedu/address/logic/parser/FindCommandParser.java]: Same as above

File: src/main/java/seedu/address/logic/parser/ParserUtil.java [hunk 4]
```diff
@@ -522,12 +525,15 @@ public static Pair<Optional<InternshipInterviewDateTime>, Optional<InternshipInt
                     argMultimap.getValue(PREFIX_RANGE_START).get());
                 LocalDateTime endDateTime = DateTimeParserUtil.parseStringToDateTimeThrow(
                     argMultimap.getValue(PREFIX_RANGE_END).get());
+                if (startDateTime.isAfter(endDateTime)) {
+                    throw new ParseException(
```
Comment (lunaroddity) [inline src/main/java/seedu/address/logic/parser/ParserUtil.java:528]: I feel like this line break is unnecessary since it fits within 120 characters

File: src/main/java/seedu/address/logic/parser/SortCommandParser.java [hunk 5]
```diff
@@ -29,8 +29,7 @@ public class SortCommandParser implements Parser<SortCommand> {
      * Regex used to confirm if the arguments is p for sort command.
```
Comment (lunaroddity) [inline src/main/java/seedu/address/logic/parser/SortCommandParser.java]: Did you mean `c` since the regex below uses `SORT_COMPANIES_ARG_WORD`?

File: src/test/java/seedu/address/model/person/NameTest.java [hunk 6]
```diff
@@ -21,21 +21,36 @@ public void constructor_invalidName_throwsIllegalArgumentException() {
...
-        assertTrue(Name.isValidName("12345")); // numbers only
-        assertTrue(Name.isValidName("peter the 2nd")); // alphanumeric characters
-        assertTrue(Name.isValidName("Capital Tan")); // with capital letters
-        assertTrue(Name.isValidName("David Roger Jackson Ray Jr 2nd")); // long names
+        // Valid names
+        assertTrue(Name.isValidName("John")); // Single word name
+        assertTrue(Name.isValidName("John Doe")); // Standard first and last name
+        //        assertTrue(Name.isValidName("Ana María")); // Name with accented characters
+        //        assertTrue(Name.isValidName("O'Conner")); // Name with apostrophe
+        //        assertTrue(Name.isValidName("D'Artagnan")); // Name with apostrophe
```
Comment (lunaroddity) [inline src/test/java/seedu/address/model/person/NameTest.java]: Are you going to keep these tests? If not, I think you can delete them

File: src/test/java/seedu/address/model/person/NameTest.java [hunk 7]
```diff
@@ -21,21 +21,36 @@ public void constructor_invalidName_throwsIllegalArgumentException() {
...
+        assertTrue(Name.isValidName("Anne Marie")); // Double first name
+        //        assertTrue(Name.isValidName("João")); // Name with non-English characters
+        //        assertTrue(Name.isValidName("François")); // Name with cedilla
```
Comment (lunaroddity) [inline src/test/java/seedu/address/model/person/NameTest.java]: Same here

File: src/test/java/seedu/address/model/person/NameTest.java [hunk 8]
```diff
@@ -21,21 +21,36 @@ public void constructor_invalidName_throwsIllegalArgumentException() {
...
+        assertFalse(Name.isValidName("John_Doe")); // Underscore
+        assertFalse(Name.isValidName("John.Doe")); // Period character
+        assertFalse(Name.isValidName("-John")); // Leading hyphen
+        assertFalse(Name.isValidName("John-")); // Trailing hyphen
+        assertFalse(Name.isValidName("John--Doe")); // Double hyphen
+        assertFalse(Name.isValidName("Anne  Marie")); // Double first name
+
+
+
+
```
Comment (lunaroddity) [inline src/test/java/seedu/address/model/person/NameTest.java]: Just a nit, I think you can delete these newliness

File: src/test/java/seedu/address/model/person/PersonTest.java [hunk 9]
```diff
@@ -44,11 +44,6 @@ public void isSamePerson() {
         // name differs in case, all other attributes same -> returns false
         Person editedBob = new PersonBuilder(BOB).withName(VALID_NAME_BOB.toLowerCase()).build();
         assertFalse(BOB.isSamePerson(editedBob));
-
-        // name has trailing spaces, all other attributes same -> returns false
```
Comment (lunaroddity) [inline src/test/java/seedu/address/model/person/PersonTest.java:48]: Why was this test deleted?

**Review by lunaroddity — COMMENTED** [review]
I think we still need to discuss a bunch of these additions

File: src/main/java/seedu/address/logic/parser/FindCommandParser.java (hunk 2 above)
Comment (Tim-Siu) [reply src/main/java/seedu/address/logic/parser/FindCommandParser.java]: Thanks for the observation! I first put a string here, but later decided to abstract is away haha. I will resolve this in the next commit.

File: src/test/java/seedu/address/model/person/NameTest.java (hunk 6 above)
Comment (Tim-Siu) [reply src/test/java/seedu/address/model/person/NameTest.java]: I previously drafted a more sophisticated regex but I didn't quite understand it haha

File: src/test/java/seedu/address/model/person/PersonTest.java (hunk 9 above)
Comment (Tim-Siu) [reply src/test/java/seedu/address/model/person/PersonTest.java:48]: The updated regex now doesn't allow trailing spaces. Actually such cases will never happen because the parser trim the string

File: docs/UserGuide.md [hunk 10]
```diff
@@ -133,6 +133,7 @@ Format: `add p n/NAME p/PHONE_NUMBER e/EMAIL a/ADDRESS [t/TAG]`
 Parameters
```
Comment (oeggy03) [inline docs/UserGuide.md:133]: Thanks for making the user guide up to date!

File: src/main/java/seedu/address/logic/parser/FindCommandParser.java [hunk 11]
```diff
@@ -81,6 +99,24 @@ public FindCommand parse(String args) throws ParseException {
             List<String> nameKeywordsList = new ArrayList<>(nameKeywords);
             List<String> tagKeywordsList = new ArrayList<>(tagKeywords);
```
Comment (oeggy03) [inline src/main/java/seedu/address/logic/parser/FindCommandParser.java:101]: Good that you added this to catch any invalid command formats!

File: src/main/java/seedu/address/logic/parser/SortCommandParser.java (hunk 5 above)
Comment (oeggy03) [inline src/main/java/seedu/address/logic/parser/SortCommandParser.java]: Hi please change this to c!

Comment (Tim-Siu) [reply src/main/java/seedu/address/logic/parser/SortCommandParser.java]: Oops thanks for catching that!

**Review by rngzhi — APPROVED** [review]

File: src/test/java/seedu/address/model/person/PersonTest.java (hunk 9 above)
Comment (lunaroddity) [reply src/test/java/seedu/address/model/person/PersonTest.java:48]: Ok sure, I think you can delete it then?
